# Generated by Django 3.0.4 on 2020-03-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_item', models.CharField(max_length=200)),
                ('added_on', models.BooleanField(default=False)),
            ],
        ),
    ]
